### ISSUE TITLE
订阅链接没有了吗？看不到

### ISSUE THREAD

**Issue by tiancool** [nameryan/iCal#10]
订阅链接没有了吗？看不到

**Comment by JasonDepp** [comment]
@tiancool 貌似是up主更新代码时候把hyperlink给搞没了，我在commit history里翻到这个：
https://p29-calendars.icloud.com/published/2/EU3uSlvFKk14FXKorvjvca_OB5AYPXND2mAhSUn3cLf2l9BfibxNgLFfkaR3IgyLbjnS9Mz9BxYODw-KQtz1w8eerO1pEnnmmasw3mdUNIM

(https://github.com/nameryan/iCal/commit/e4ee60557e6d40564cc6c95e73a33e2a03015c4b)

**Comment by hyoukadev** [comment]
> 订阅链接没有了吗？看不到

@tiancool UP 把链接从 https 更新成 webcal 了，似乎 github 的 markdown 没有正确生成出链接，需要你查看 [README.md](https://raw.githubusercontent.com/nameryan/iCal/master/README.md) 的源码

**Comment by makerjackie** [comment]
正好在找一些实用的公共日历，赞一个
