### ISSUE TITLE
上海进博会

### ISSUE THREAD

**Issue by ZhishiX** [nameryan/iCal#6]
上海进博会等私人内容被误加入到公共日历

**Comment by nameryan** [comment]
上海进博会并非私人日历，考虑到如果订阅者生活在上海，这个提示是非常有必要的。
当然对于非上海地区的朋友可能有些打扰，也因此在日历中注明了是上海进博会，对此带来的不便请谅解。
也非常感谢您的及时建议，欢迎提出其他的需求。

**Comment by ZhishiX** [comment]
好的，感谢公共日历的持续更新～
