### ISSUE TITLE
国庆节是不是错了呀 

### ISSUE THREAD

**Issue by BruceWind** [nameryan/iCal#7]
感谢大佬做这个,  国庆应该是10月1-7吧  不是 30, 10月1-6吧

**Comment by v1c77** [comment]
按 网上的说法. 

> 10月1日 - 10月7 日 为法定节假日.   9月29和10月12 补班. 

你仔细看作者 有在 28号多补一天班.. 所以他应该是 打算 9月28 日 跟 9月30日调休....


不过确实, 10月7日是应该 算十一休假的. @nameryan
