### ISSUE TITLE
这个日历你是怎么做的？能不能导入到google calendar？

### ISSUE THREAD

**Issue by cuilei5205189** [nameryan/iCal#8]

**Comment by cuilei5205189** [comment]
你的链接可以导入google calendar。
但是我自己用mac导出的链接，和你的不太一样，不能导入google。
![image](https://user-images.githubusercontent.com/20814679/50505125-dbcfeb80-0aac-11e9-819b-078b71a4e674.png)
想请教一下你是怎么导出的日历。

**Comment by cuilei5205189** [comment]
直接导出ics文件可以，但是这样共享者修改之后，就不能同步更新了吧。
你的这个链接是怎么导出来的。
https://p29-calendars.icloud.com/published/2/EU3uSlvFKk14FXKorvjvca_OB5AYPXND2mAhSUn3cLf2l9BfibxNgLFfkaR3IgyLbjnS9Mz9BxYODw-KQtz1w8eerO1pEnnmmasw3mdUNIM

**Comment by cuilei5205189** [comment]
找到问题所在了，打开webcal链接时，会显示http的链接。
<img width="566" alt="2018-12-28 2 52 55" src="https://user-images.githubusercontent.com/20814679/50505852-d1afec00-0ab0-11e9-88d7-9d8f9f1ea95b.png">

**Comment by nameryan** [comment]
对的，你已经琢磨出来了：）
